# Generated by Django 3.2.6 on 2021-09-30 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='orderitem',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
