# Generated by Django 3.2.6 on 2021-09-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210922_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
