# Generated by Django 3.2.6 on 2021-09-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210923_0827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyText',
        ),
    ]
