# Generated by Django 3.2.6 on 2021-09-23 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_mytext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
