# Generated by Django 3.2.6 on 2021-09-23 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
